version: '3.9'

services:
  eventmodularmonolith.database:
      image: postgres:latest
      container_name: EMM.Database
      environment:
        - POSTGRES_DB=emm
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./.containers/db:/var/lib/postgresql/data
      ports:
        - 5432:5432

  eventmodularmonolith.seq:
      image: datalust/seq:latest
      container_name: EMM.Seq
      environment:
        - ACCEPT_EULA=Y
      ports:
        - 5341:5341
        - 8081:80

  eventmodularmonolith.api:
    image: ${DOCKER_REGISTRY-}eventmodularmonolithapi
    container_name: EMM.Api
    build:
      context: .
      dockerfile: src/API/EventModularMonolith.Api/Dockerfile
    ports:
        - 5000:8080
        - 5001:8081

  eventmodularmonolith.redis:
      image: redis:latest
      container_name: EMM.Redis
      restart: always
      ports:
        - 6379:6379

  eventmodularmonolith.webapp:
    image: eventsapp
    build:
      context: src/WebApps/MainWebsite/events-app
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3005:3000


