version: '3.9'

services:
  eventmodularmonolith.database:
      image: postgres:latest
      container_name: EMM.Database
      environment:
        - POSTGRES_DB=emm
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./.containers/db:/var/lib/postgresql/data
      ports:
        - 5432:5432

  eventmodularmonolith.seq:
      image: datalust/seq:latest
      container_name: EMM.Seq
      environment:
        - ACCEPT_EULA=Y
      ports:
        - 5341:5341
        - 8081:80

  eventmodularmonolith.api:
    image: ${DOCKER_REGISTRY-}eventmodularmonolithapi
    container_name: EMM.Api
    build:
      context: .
      dockerfile: src/API/EventModularMonolith.Api/Dockerfile
    ports:
        - 5000:8080
        - 5001:8081

  eventmodularmonolith.redis:
      image: redis:latest
      container_name: EMM.Redis
      restart: always
      ports:
        - 6379:6379

  eventmodularmonolith.webapp:
    image: eventsapp
    container_name: EMM.WebApp
    build:
      context: src/WebApps/MainWebsite/events-app
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3005:3000

  azurite:
     image: mcr.microsoft.com/azure-storage/azurite:latest
     container_name: EMM.BlobStorage
     environment:
        - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
     volumes:
        - ./.containers/blob_storage/data:/data
     ports:
        - "10000:10000"
     command: "azurite-blob --blobHost 0.0.0.0 -l /data --debug /debug.log"

  eventmodularmonolith.identity:
     image: quay.io/keycloak/keycloak:latest
     container_name: EMM.Identity
     command: start-dev --import-realm
     environment:
        - KC_HEALTH_ENABLED=true
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KEYCLOAK_LOGLEVEL=TRACE
     volumes:
        - ./.containers/identity:/opt/keycloak/data
        - ./.files:/opt/keycloak/data/import
     ports:
        - 18080:8080

