// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EventModularMonolith.Modules.Users.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class FixModeratorsTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameTable(
                name: "Moderators",
                schema: "users",
                newName: "moderators",
                newSchema: "users");

            migrationBuilder.AddColumn<bool>(
                name: "is_active",
                schema: "users",
                table: "moderators",
                type: "boolean",
                nullable: false,
                defaultValue: false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "is_active",
                schema: "users",
                table: "moderators");

            migrationBuilder.EnsureSchema(
                name: "Users");

            migrationBuilder.RenameTable(
                name: "moderators",
                schema: "users",
                newName: "Moderators",
                newSchema: "Users");
        }
    }
}
