// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EventModularMonolith.Modules.Events.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddOrganizerToVenue : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "organizer_id",
                schema: "events",
                table: "venues",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.CreateIndex(
                name: "ix_venues_organizer_id",
                schema: "events",
                table: "venues",
                column: "organizer_id");

            migrationBuilder.AddForeignKey(
                name: "fk_venues_organizer_organizer_id",
                schema: "events",
                table: "venues",
                column: "organizer_id",
                principalSchema: "events",
                principalTable: "organizer",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_venues_organizer_organizer_id",
                schema: "events",
                table: "venues");

            migrationBuilder.DropIndex(
                name: "ix_venues_organizer_id",
                schema: "events",
                table: "venues");

            migrationBuilder.DropColumn(
                name: "organizer_id",
                schema: "events",
                table: "venues");
        }
    }
}
