//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EventModularMonolith.Modules.Events.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Venues : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "location",
                schema: "events",
                table: "events");

            migrationBuilder.AddColumn<Guid>(
                name: "venue_id",
                schema: "events",
                table: "events",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.CreateTable(
                name: "venues",
                schema: "events",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    organizer_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "text", nullable: false),
                    description = table.Column<string>(type: "text", nullable: false),
                    address_street_and_number = table.Column<string>(type: "text", nullable: false),
                    address_city = table.Column<string>(type: "text", nullable: false),
                    address_region = table.Column<string>(type: "text", nullable: false),
                    address_country = table.Column<string>(type: "text", nullable: false),
                    address_longitude = table.Column<double>(type: "double precision", nullable: false),
                    address_latitude = table.Column<double>(type: "double precision", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_venues", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_events_venue_id",
                schema: "events",
                table: "events",
                column: "venue_id");

            migrationBuilder.AddForeignKey(
                name: "fk_events_venues_venue_id",
                schema: "events",
                table: "events",
                column: "venue_id",
                principalSchema: "events",
                principalTable: "venues",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_events_venues_venue_id",
                schema: "events",
                table: "events");

            migrationBuilder.DropTable(
                name: "venues",
                schema: "events");

            migrationBuilder.DropIndex(
                name: "ix_events_venue_id",
                schema: "events",
                table: "events");

            migrationBuilder.DropColumn(
                name: "venue_id",
                schema: "events",
                table: "events");

            migrationBuilder.AddColumn<string>(
                name: "location",
                schema: "events",
                table: "events",
                type: "text",
                nullable: false,
                defaultValue: "");
        }
    }
}
